image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

#test:
#  stage: test
#  script:
#:    - mvn $MAVEN_CLI_OPTS test

before_script:
    - which java
    - java -version
